### ISSUE TITLE
Adding new items doesn't save for some users.

### ISSUE THREAD

**Issue by jjwoma** [mohitbagra/vsts-extensions#57]
Some users in our DevOps org, cannot create new or see existing check list items.  
Example user has a basic license.  When they type they are just presented with an X and the item never saves when moving off the screen.
Other users with the same license can see and save items.

Ideas on how we can resolve?
![image](https://user-images.githubusercontent.com/38021935/56831011-9ee2ee00-682d-11e9-8eb1-fe5753de6c10.png)

**Comment by mohitbagra** [comment]
I have published a new update of the extension. Can you let me know if this works now?

**Comment by jjwoma** [comment]
Hi, we confirmed the new vert updated in our tenant, but the update doesn't appear to resolve the issue. The extension also seemed to cause spinning on the loading of project boards, which would make it so that people couldn't save changes to until the checklist extension finished loading. Unfortunately we ended up disabling the extension since it was impacting our overall user experience.
