### ISSUE TITLE
Work item checklist - does not inherit dark theme

### ISSUE THREAD

**Issue by inovacode** [mohitbagra/vsts-extensions#61]
The extension Work item checklist doesn't inherit the dark theme.

https://marketplace.visualstudio.com/items?itemName=mohitbagra.workitem-checklist

**Comment by mohitbagra** [comment]
I'll be publishing an update over the weekend which will add this support

**Comment by inovacode** [comment]
You're awesome, thanks!!

**Comment by inovacode** [comment]
@mohitbagra How is the dark theme activated?  I don't see it in settings and the theme for the work item checklist extension still has a while background.

**Comment by mohitbagra** [comment]
I published an update today which supports dark theme.

**Comment by LSTANCZYK** [comment]
@mohitbagra I see your comment about publishing new version with dark theme in 2019, but it is 2026 and I am still not able to see it. Any hints?
